sudo: false
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
script:
  - coverage3 run --source=ate -m unittest discover
after_success:
  - coveralls3
