sudo: false
language: python3
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
install:
  - pip3 install -r requirements_dev.txt
script:
  - coverage3 run --source=ate -m unittest discover
after_success:
  - coveralls3
